### ISSUE TITLE
Payments & Subscriptions screen unclear

### ISSUE THREAD

**Issue by oriz456** [DiviProject/Divi-Desktop-Public#100]
![image](https://user-images.githubusercontent.com/32154971/66611243-e2d37080-eb8b-11e9-9feb-7fa0fce0cd46.png)

I had 4 subscriptions, 2 of them were canceled before they were expired(but they are expired now). However this only shows an option to delete one token and says "expires 09/17"(should just say expired in that case since it was last month). This is but one of the canceled ones. The other 3 show N/A for expiration date(even though 2 of them are still active), and allow for cancelling of the subscription of all 3. 

This should also be hidden in advanced mode to prevent people from accidentally deleting their active tokens.

┆Attachments: <a href="https://storage.www.wrike.com/attachments/115001422?accountId=2811331">IMAGE 2019-10-24 13:13:06.jpg</a> | <a href="https://storage.www.wrike.com/attachments/115001429?accountId=2811331">IMAGE 2019-10-24 13:13:08.jpg</a> | <a href="https://storage.www.wrike.com/attachments/115001435?accountId=2811331">IMAGE 2019-10-24 13:13:11.jpg</a>

**Comment by Divicoin** [comment]
➤ Abigail Loaiza Rojas commented:

Thease are some requests from the Beta Bashers. Please check the images and comments.

Comments:

"These are little tweaks nothing big but you need to resize the default desktop app to be comforatble viewing... maybe something for later... not a huge priority"

"Im sure you all know but unconfirmed doesnt work either
at least for a move but I will try with an external send"

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

Size issue has been fixed. We are unable to controll UNCONFIRMED balance value as it is being return from daemon's 'getwalletinfo'

**Comment by Divicoin** [comment]
➤ Abigail Loaiza Rojas commented:

Eugene Ilagin Thanks.

**Comment by oriz456** [comment]
-shouldn't expired tokens be deleted automatically? right now it says "expires" and shows a date that's already in the past. Lets just either remove them or instead of a date, show "expired".

-Still active tokens should show "Active" instead of "NA".

-This should be changed to "are you sure you want to delete payment token?"

![image](https://user-images.githubusercontent.com/32154971/67629829-dc631b00-f852-11e9-9db1-9d62d4d3baf0.png)

**Comment by Divicoin** [comment]
➤ Eugene Ilagin commented:

done

**Comment by oriz456** [comment]
"are you sure to delete payment token?" change to "are you sure you want to delete payment token?" still not done

**Comment by dkostenevich** [comment]
done v1.5.2

**Comment by oriz456** [comment]
All good
